name: Deploy a JS Express API to App Services

on:
  push:
    branches: [ master ]

jobs:
  JS to App Service Deployment:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Azure Login
      uses: Azure/login@v1.1
      with:
        # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
        creds: ${{ azure_creds }}
        enable-AzPSSession: true
